global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'vss-demiurge'
    environment: 'production'

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - "alerts/*.yaml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'vss-ottb'
    static_configs:
      - targets: ['vss-ottb:8083']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'vss-dci'
    static_configs:
      - targets: ['vss-dci:8082']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'vss-point'
    static_configs:
      - targets: ['vss-point:8081']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'vss-workspace'
    static_configs:
      - targets: ['vss-workspace:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq-exporter:9419']
    scrape_interval: 15s

  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s

